name: shape-guided-diffusion
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.10
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.10.2
  - torchvision=0.11.3
  - numpy=1.22.3
  - pip:
    - diffusers==0.6.0
    - transformers==4.22.1
    - accelerate==0.12.0
    - opencv-python==4.2.0.34
    - pycocotools==2.0.5
    - scipy==1.9.1
    - ftfy==6.1.1
    - timm==0.6.11
    - clean-fid==0.1.35
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip